SIM          ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES  = $(PWD)/../src/tt_um_sushma1012_lfsr_prng.v
TOPLEVEL         = tt_um_suhsma1012_lfsr_prng
MODULE           = test_lfsr_prng

include $(shell cocotb-config --makefiles)/Makefile.sim
